eureka:
  client:
    serviceUrl:
        defaultZone: http://localhost:9876/eureka
    enabled: true

zuul:
  routes:
    registration: /registrationui/**
    donor: /donorui/**

---
# Pass Authorization header downstream
zuul:
  sensitiveHeaders: Cookie,Set-Cookie,Authorization